### ISSUE TITLE
Interface Bug (probably compatability)

### ISSUE THREAD

**Issue by Foozey** [MrCrayfish/GoblinTraders#36]
Issue is shown [here](https://gyazo.com/70295dd004f2e9072f8b03f754d03105). This is most likely a compatibility issue with AppleSkin, which is the mod that adds the food info tooltips. Either way, definitely worth investigating due to how commonly the AppleSkin mod is used.

**Comment by MrCrayfish** [comment]
I would fix if I could but I am using the villager trading GUI, not a custom GUI. Problems lies more with AppleSkin.

**Comment by MrCrayfish** [comment]
Can you test this with a villager with custom trades? It's possible the issue hasn't been seen before because Villagers by default don't accept food as a buy item. If this is an issue, please create an issue on AppleSkin and reference this thread.
`/summon villager ~ ~1 ~ {VillagerData:{profession:farmer,level:2,type:plains},Offers:{Recipes:[{buy:{id:apple,Count:1},sell:{id:apple,Count:1},rewardExp:0b,maxUses:9999999}]}}`

**Comment by MrCrayfish** [comment]
Okay, so I tested myself. No issues...
![image](https://user-images.githubusercontent.com/4958241/118350411-a51fa080-b595-11eb-82ca-8d0b110a21f1.png)

**Comment by Foozey** [comment]
Hrm, did you have OptiFine installed as well during your test?

**Comment by MrCrayfish** [comment]
There's your problem

**Comment by MrCrayfish** [comment]
Regardless of the issue, nothing I can do because I simply use the Villager trade GUI. Follow up with the AppleSkin dev.

Another commands for Villager with more trades if you need to test if the issue happens with villagers too.
`/summon villager ~ ~1 ~ {VillagerData:{profession:farmer,level:2,type:plains},Offers:{Recipes:[{buy:{id:apple,Count:1},sell:{id:apple,Count:1},rewardExp:0b,maxUses:9999999},{buy:{id:bread,Count:1},sell:{id:bread,Count:1},rewardExp:0b,maxUses:9999999}]}}`

**Comment by Foozey** [comment]
Ah yep, happening with villagers as well. I'll notify the AppleSkin dev.
