### ISSUE TITLE
issues with dark enchanter mod

### ISSUE THREAD

**Issue by RobGod389** [MrCrayfish/GoblinTraders#55]
so i took a fishing rod with luck of the sea 5 after trading with the goblin to the Dark enchanter by frqnny and when i added luck of the sea 5 and other enchantments , the luck of the sea 5 disappeared from the fishing rod

**Comment by RobGod389** [comment]
theres also an issue with a mod called Infusion table (jptrzy). Where i traded with the goblin for a efficiency 6 tool and used the infusion table to transfer the enchantment onto a book to freely apply it to any tool. What it came out to be is that the book cannot be applied to anything making it useless. i have raised this issue in the other mod as well

**Comment by MrCrayfish** [comment]
It's because overlevelled enchantments aren't really designed to work with the game. I've patched in my mod at the minimum an issue when merging tools in an anvil that it doesn't reset the enchantment level to it's max level. The only fix is that other mods consider enchantments with levels above their max level.
